### ISSUE TITLE
signed overflow on 16bit

### ISSUE THREAD

**Issue by tankf33der** [bitcoin-core/ctaes#15]
FYI.

I have setup [demo](https://github.com/tankf33der/ctaes-tis) repo to run ctaes tests under [TIS-CI](https://ci.trust-in-soft.com/).

Report of test run you can find [here](https://ci.trust-in-soft.com/projects/tankf33der/ctaes-tis/1) and check "undefined behaviour" in list for 16bit platforms.

Known members of [TIS](https://trust-in-soft.com/) team in github are: @pascal-cuoq and @guillaumemillot

**Comment by sipa** [comment]
@tankf33der Thanks for analyzing this. Could you see if #18 fixes this?

**Comment by tankf33der** [comment]
> @tankf33der Thanks for analyzing this. Could you see if #18 fixes this?

@sipa, LoadByte function fixed and now TIS [found](https://ci.trust-in-soft.com/projects/tankf33der/ctaes-tis/2?page=1&filter=status=ub) next one. I could somehow enable option "dont stop after first alarm and keep running", but lets do it one by one.

**Comment by sipa** [comment]
@tankf33der Try agian.

**Comment by tankf33der** [comment]
@sipa 

All [green](https://ci.trust-in-soft.com/projects/tankf33der/ctaes-tis/3?page=1), issue closed.

**Comment by sipa** [comment]
Awesome, thanks!
